#!/bin/sh

set -e

chown -R 501:501 /var/mobile/Documents/.pojavlauncher
chmod -R 0755 /var/mobile/Documents/.pojavlauncher

echo " "
echo "PojavLauncher has been installed! Take a look at the wiki to learn more about PojavLauncher at https://bit.ly/2PgpexZ."

